### ISSUE TITLE
Cannot edit some fields

### ISSUE THREAD

**Issue by jhuddle61** [NEORIS-ZDEVOPS/DS-Editor#2] opened 2023-07-31 11:54 UTC
Some of the fields in my dataset are shown in yellow and will not allow me to save changes to those fields. Is there something I can do to allow these fields to be editable?

![image](https://github.com/NEORIS-ZDEVOPS/DS-Editor/assets/26878954/ddf4ff11-7af0-4b70-81f1-801f21f8ae22)

**Comment by jhuddle61** [comment] 2023-07-31 17:40
Found that fields defined as PIC 9 will not save edits. Is this by design?

**Comment by antonkc** [comment] 2023-07-31 18:19
No, It should be editable. Today I am on vacation, I will try to recreate this problem tomorrow. Further information then.

**Comment by jhuddle61** [comment] 2023-07-31 19:03
More info, I tried with a couple of values, one date and one integer both PIC 9, zeroes were saved for the value versus what I typed.

**Comment by antonkc** [comment] 2023-07-31 19:20
It may be because the input is not validating. A better feedback system is in my backlog for these potential cases. Can you provide the full PIC and what numbers you tried to type in?

**Comment by antonkc** [comment] 2023-08-01 06:36
Error reproduced

**Comment by antonkc** [comment] 2023-08-02 13:11
Fix will roll in the next version. We plan to deploy a minor one this friday.

**Comment by jhuddle61** [comment] 2023-08-07 17:22
Did the minor release get pushed last Friday?

**Comment by antonkc** [comment] 2023-08-07 17:36
No, sorry. The code is ready, so I expect it to be published soon. The version number will 1.4.1 then.

PD: I didn't forget about this issue. You can expect an update as soon as the version rolls out.

**Comment by antonkc** [comment] 2023-08-09 11:14
Some pipeline work must be done here, sorry. The one that uploads the artifact is a management person. I will try to get clearance to do it myself or with some script. Meanwhile, I am still stuck waiting with you.

I was too enthusiastic about the first issue opened by users that I jumped to giving dates without checking with said business person. Mistake on me.

Like a said before, I did not forget this issue and I will inform you as soon as it is realeased.

**Comment by antonkc** [comment] 2023-08-09 21:27
Okey, @jhuddle61. The minor version just rolled out. I will update the repo tomorrow since today is getting a bit late. You should be able to edit these fields already.

**Comment by antonkc** [comment] 2023-08-10 08:50
I will close this issue since the version 1.4.1 fixes it.

**Closed as completed by antonkc** 2023-08-10 08:50 UTC
Labels: bug
